Fix #293: AttributeError: 'SshMachine' object has no attribute 'env' (#347)
* Allow _setdoc() to fetch docstring from a function with different name

* Make BaseRemoteMachine.path() not depend on env

Closes #293 AttributeError: 'SshMachine' object has no attribute 'env'

* Revert "Allow _setdoc() to fetch docstring from a function with different name"

This reverts commit 1b410588970098fcfbc2a8b0c0fa7e71f1cfd637.

* Share docstrings from BaseRemoteMachine to RemoteEnv.expand*()

* Fix docstring assignment problem with Py2.X